2020-03-17 16:05:05,210 ERROR: Exception on /user/flask dev [GET] [in /home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sarthakc/Desktop/microblog/app/routes.py", line 75, in user
    return render_template('user.html',user=user,posts=posts)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sarthakc/Desktop/microblog/app/templates/user.html", line 19, in template
    <p><a href="{{ url_for('unfollow',username=user.username') }}">UNFOLLOW</a></p>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'string'
2020-03-17 16:05:51,122 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 16:12:17,196 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 17:46:39,312 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 17:51:38,296 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 17:53:14,805 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 19:18:17,608 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 23:21:12,849 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 23:21:16,339 ERROR: Exception on / [GET] [in /home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sarthakc/Desktop/microblog/app/routes.py", line 25, in index
    posts = current_user.followed_posts().paginate(page,app.config['POST_PER_PAGE'],False)
KeyError: 'POST_PER_PAGE'
2020-03-17 23:23:38,436 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-17 23:25:02,432 ERROR: Exception on /explore [GET] [in /home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sarthakc/Desktop/microblog/app/routes.py", line 143, in explore
    return render_template('index.html',title='Explore', posts=posts,next_url=next_url,prev_url=prev_url)# as we dont want post form in this page so there is no form argument.
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sarthakc/Desktop/microblog/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sarthakc/Desktop/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/sarthakc/Desktop/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/sarthakc/Desktop/microblog/app/templates/index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-03-17 23:26:04,231 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:50]
2020-03-18 01:04:48,006 INFO: Microblog startup [in /home/sarthakc/Desktop/microblog/app/__init__.py:51]
